server:
  port: 8080

spring:
  application:
    name: cetc38-studySystem
  
  datasource:
    url: jdbc:mysql://localhost:3306/study_system
    username: cetc38
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# JWT配置
jwt:
  secret: ZWNldGMzOFN0dWR5U3lzdGVtU2VjcmV0S2V5MjAyNEZvckpXVFRva2VuR2VuZXJhdGlvbkFuZFZhbGlkYXRpb25XaXRoU2VjdXJlTGVuZ3Ro
  expiration: 86400000  # 24小时，单位：毫秒

# 日志配置
logging:
  level:
    org.springframework.security: DEBUG
    com.cetc38.studysystem: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

